app:
  jsonplaceholder:
    host: https://jsonplaceholder.com
    items: 20
    password: password
    port: 80
    user: user
logging:
  level:
    com.example.bookmarks: INFO
  pattern:
    dateformat: yyyy-MM-dd'T'HH:mm:ss
  include-application-name: false
spring:
  application:
    name: bookmarks-mizo-masaru
  datasource:
    password: bookmarks
    url: jdbc:postgresql://localhost:5488/bookmarks
    username: postgres
  h2:
    console:
      enabled: true

